apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  APP_ENV: test14
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: myapp-pod
#   labels:
#     app.kubernetes.io/name: MyApp
#   annotations:
#     argocd.argoproj.io/sync-options: Replace=true
# spec:
#   containers:
#   - name: app
#     image: busybox:1.28
#     command: ['sh', '-c', "sleep 2"]
#   restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-slack-notification-14
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    argocd.argoproj.io/sync-wave: "-1"
    #argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: zerosuxx/alpine
        command:
          - echo
          - "Hello World 14"
      restartPolicy: Never
  backoffLimit: 3
