apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  APP_ENV: test3
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "sleep 5"]
---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   generateName: app-slack-notification-
#   #name: app-slack-notification
#   #annotations:
#   #  argocd.argoproj.io/hook: PostSync
#   #  argocd.argoproj.io/hook-delete-policy: HookSucceeded
# spec:
#   template:
#     spec:
#       containers:
#       - name: slack-notification
#         image: zerosuxx/alpine
#         command:
#           - echo
#           - "Hello World"
#       restartPolicy: Never
#   backoffLimit: 3
